### ISSUE TITLE
Collider bugs

### ISSUE THREAD

**Issue by codingwatching** [HyFabi/Blocket#2]
Hi @HyFabi 
When open game we see that the player can not landing on the dirt because of the collider of the chunk, please check

![image](https://user-images.githubusercontent.com/85933804/140945536-c895bc4e-ea29-48b5-bcc7-d660f26470e3.png)

Thank you!

**Comment by Cse19455** [comment]
Ok ,
I think you have not inserted the right tile for the ores that should spawn 
(Stone is coded as an ore right now => will be changed in the future)
[Sadly , I have changed the settup a bit so the screenshot will not look the same] 
![image](https://user-images.githubusercontent.com/59655496/140949780-de1054a7-79e8-4d44-a09b-30a66e21e5d3.png)

You can see , there are tiles that are not displayed in youre version.

Our team is struggling a bit , because Unity somehow manages to destroy Prefabs as well as Tile Files.

![image](https://user-images.githubusercontent.com/59655496/140950188-5ac2f5a7-2db1-44bb-9d86-cc8165f537cb.png)
(If my prediction is correct , you should see a purple symbol for the tiles that can not load for some reason)

But thank you for the interest in our Project :)

**Comment by HyFabi** [comment]
Hi!

That bug is just a missing texture. In the next commits this will going to be fixed.
